receivers:
  otlp:
    protocols:
      grpc:           # default port 4317
      http:           # default port 4318

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true          # tempo ภายใน network → ไม่ต้อง TLS
  prometheus:
    endpoint: "0.0.0.0:8889"  # collector จะ expose metric ให้ Prometheus scrape

processors:
  batch: {}                   # รวม record ก่อนส่ง (ปรับ batch size ได้)

service:
  pipelines:
    traces:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [otlp/tempo]
    metrics:
      receivers:  [otlp]
      processors: [batch]
      exporters:  [prometheus]