spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bank
    username: postgres123
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

  zipkin:
    base-url: http://localhost:9411
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
