services:
  keycloak-lab4:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak-lab4
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    networks:
      - lab4-net

networks:
  lab4-net:
    driver: bridge