services:
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_tracer
    ports:
      - "9411:9411"

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: postgres123
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pgdata_clean:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  pgdata_clean: