services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak-lab5
    command: start-dev
    ports:
      - "8100:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - keycloak-net

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - keycloak-net

networks:
  keycloak-net:
    driver: bridge