server:
  port: 8081

keycloak:
  realm: keycloak-MFA-lab5
  client-id: pc-agent
  base-url: http://localhost:8100/realms/keycloak-MFA-lab5
  device-code-endpoint: ${keycloak.base-url}/protocol/openid-connect/auth/device
  token-endpoint: ${keycloak.base-url}/protocol/openid-connect/token
  userinfo-endpoint: ${keycloak.base-url}/protocol/openid-connect/userinfo